### ISSUE TITLE
Remove/Add Margin

### ISSUE THREAD

**Issue by SafeDuck** [acm-ucr/vex-robotics-website#87]
![image](https://github.com/acm-ucr/vex-robotics-website/assets/49844738/e9731ab3-4e4a-4665-af0e-353cf3fd9088)

1. In `Companies.jsx` remove the margin bottom 
2. In Footer.jsx add 10 units of margin top

This is better because it will apply on all pages, not just on the home page

**Comment by GitHaresco** [comment]
![image](https://github.com/acm-ucr/vex-robotics-website/assets/162786819/39311610-93c3-41a9-98c6-5f763c0ee771)
